using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// 기존 플레이어 데이터셋의 클래스형태로 불러왔던 데이터들을 index 값만 불러온 경량화 데이터타입
public class PlayerRawInfo {
	public int playerInfoIndex;
	public int playerSkillIndex;
	public int? starterPackIndex;
	public int?[] equipedEquipment;
	public int? portraitIndex;
	public string name;
	public int statHp;
	public int statStr;
	public int statInt;
	public int statDex;
	public int statAp;
	public int statExtraDraw;
	public int gold;
	public int level;
	public int exp;
	public int maxHp;
	public int currentHp;
	public int maxAp;
	public int currentAp;
	public int skillPoint;
	public List<CardLiteDBData> playerDeckIndexList;
	public List<CardLiteDBData> playerBagIndexList;
	public List<int> clearedAreaIndexList;
	public List<int> unlockedEquipmentIndexList;
	public List<int> unlockedActiveSkillIndexList;
	public List<int> unlockedPassiveSkillIndexList;
	public List<int> newUnlockedJournalIndexList;
	public List<int> newUnlockedCharacterIndexList;
	public List<int> playedEventIndexList;
	public List<int> queuedEventIndexList;
	public int? currentAreaIndex;
	public int? currentEventIndex;
	public int? currentBattleIndex;
	public int? currentEventCount;
	public List<int> selectedStorySelectionIndexList;
	public List<int> currentEndingIndexList;
	public int? currentDeadEndingIndex;
	public int? currentDeadEndingSentenceIndex;
	public int? currentSceneIndex;
	public int? seedValue;
	public int? currentMapIndex;
	public List<int> currentRevealedAreaIndexList;
	public int? currentEncounterRerollCount;
	public Dictionary<ENUM_PLAYER_STATISTICS_TYPE, string> statistics;
}
