using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataParser
{
	internal static class QueryColumnNameStrings
	{
		public static readonly string DeadEndingSentenceIndex = "example_column_01";
		public static readonly string RevealAreaIndex = "example_column_02";
		public static readonly string ForcedRewardCardCount = "example_column_03";
		public static readonly string ForcedRewardCardTableIndex = "example_column_04";
		public static readonly string ForcedLostCardCount = "example_column_05";
		public static readonly string ForcedLostCardTableIndex = "example_column_06";
		public static readonly string IllustIndexColumn = "example_column_07";
		public static readonly string PrefabIndexColumn = "example_column_08";
		public static readonly string StorySelectionIndexListColumn = "example_column_09";
		public static readonly string SoundIndexColumn = "example_column_10";
		public static readonly string StorySentenceIndexColumn = "example_column_11";
		public static readonly string Ko_krColumn = "example_column_12";
		public static readonly string StorySelectionIndexColumn = "example_column_13";
		public static readonly string NextStorySentenceIndexListColumn = "example_column_14";
		public static readonly string BattleIndexColumn = "example_column_15";
		public static readonly string NextStoryEventColumn = "example_column_16";
		public static readonly string MinigamePrefabIndexColumn = "example_column_17";
		public static readonly string TeleportAreaIndexColumn = "example_column_18";
		public static readonly string DeadEndingIndexColumn = "example_column_19";
		public static readonly string AddEndingIndexListColumn = "example_column_20";
		public static readonly string StorySelectionRequireCurrentHpMinColumn = "example_column_21";
		public static readonly string StorySelectionRequireCurrentHpMaxColumn = "example_column_22";
		public static readonly string StorySelectionRequireHpMinColumn = "example_column_23";
		public static readonly string StorySelectionRequireHpMaxColumn = "example_column_24";
		public static readonly string StorySelectionRequireApMinColumn = "example_column_25";
		public static readonly string StorySelectionRequireApMaxColumn = "example_column_26";
		public static readonly string StorySelectionRequireStrMinColumn = "example_column_27";
		public static readonly string StorySelectionRequireStrMaxColumn = "example_column_28";
		public static readonly string StorySelectionRequireDexMinColumn = "example_column_29";
		public static readonly string StorySelectionRequireDexMaxColumn = "example_column_30";
		public static readonly string StorySelectionRequireIntMinColumn = "example_column_31";
		public static readonly string StorySelectionRequireIntMaxColumn = "example_column_32";
		public static readonly string StorySelectionRequireCardNumberColumn = "example_column_33";
		public static readonly string StorySelectionRequireCardTableIndexColumn = "example_column_34";
		public static readonly string StorySelectionRequireGoldMinColumn = "example_column_35";
		public static readonly string StorySelectionRequireGoldMaxColumn = "example_column_36";
		public static readonly string StorySelectionRequireAchievementPointMinColumn = "example_column_37";
		public static readonly string StorySelectionRequireAchievementPointMaxColumn = "example_column_38";
		public static readonly string StorySelectionRequireReputationIndexColumn = "example_column_39";
		public static readonly string StorySelectionRequireReputationMaxColumn = "example_column_40";
		public static readonly string StorySelectionRequireReputationMinColumn = "example_column_41";
		public static readonly string RewardHpColumn = "example_column_42";
		public static readonly string RewardGoldColumn = "example_column_43";
		public static readonly string RewardExpColumn = "example_column_44";
		public static readonly string RewardCardCountColumn = "example_column_45";
		public static readonly string RewardCardTableIndexColumn = "example_column_46";
		public static readonly string LostCardCountColumn = "example_column_47";
		public static readonly string LostCardTableIndexColumn = "example_column_48";
		public static readonly string RewardEquipmentCountColumn = "example_column_49";
		public static readonly string RewardEquipmentTableIndexColumn = "example_column_50";
		public static readonly string RewardJounalIndexListColumn = "example_column_51";
		public static readonly string ReputationIndexColumn = "example_column_52";
		public static readonly string ReputationAddValueColumn = "example_column_53";
		public static readonly string ReputationSetValueColumn = "example_column_54";
		public static readonly string RewardCollectionCharacterIndexList = "example_column_55";
		public static readonly string StoryEventIndexColumn = "example_column_56";
		public static readonly string IsInitialColumn = "example_column_57";
		public static readonly string InitialStorySentenceIndexColumn = "example_column_58";
		public static readonly string WeightColumn = "example_column_59";
		public static readonly string PropertyColumn = "example_column_60";
		public static readonly string ReputationMinColumn = "example_column_61";
		public static readonly string ReputationMaxColumn = "example_column_62";
		public static readonly string BgmSoundIndexColumn = "example_column_63";
		public static readonly string HintTypeColumn = "example_column_64";
		public static readonly string TargetAreaIndexListColumn = "example_column_65";
		public static readonly string StoryShopIndexColumn = "example_column_66";
		public static readonly string CardDiscountGradeColumn = "example_column_67";
		public static readonly string CardCountColumn = "example_column_68";
		public static readonly string CardTableIndexColumn = "example_column_69";
		public static readonly string EquipmentDiscountGradeColumn = "example_column_70";
		public static readonly string EquipmentCountColumn = "example_column_71";
		public static readonly string EquipmentTableIndexColumn = "example_column_72";
		public static readonly string StoryShopBuySelectionIndexColumn = "example_column_73";
		public static readonly string StoryShopNonBuySelectionIndexColumn = "example_column_74";
		public static readonly string MapIndexColumn = "example_column_75";
		public static readonly string ReputationRequirementPresetIndexColumn = "example_column_76";
		public static readonly string ReputationRequirementPresetIndexListColumn = "example_column_77";
		public static readonly string DeleteNextStoryEventColumn = "example_column_78"; 
		public static readonly string EventTypeColumn = "example_column_79";
		public static readonly string IsExclusiveColumn = "example_column_80";
		public static readonly string FactionEnumColumn = "example_column_81";
		public static readonly string IsRestColumn = "example_column_82";
		public static readonly string IsShopColumn = "example_column_83";
		public static readonly string IsDangerColumn = "example_column_84";
		public static readonly string EndGameColumn = "example_column_85";
		public static readonly string EventIllustIndexColumn = "example_column_86";
		public static readonly string ImagePathColumn = "example_column_87";
		public static readonly string ProductIDColumn = "example_column_88";
		public static readonly string NeedEnergyColumn = "example_column_89";
	}
}
