using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExlixDataConverter
{
	internal static class QueryColumnNameStrings
	{
		public static readonly string DeadEndingSentenceIndex = "dead_ending_sentence_index";
		public static readonly string RevealAreaIndex = "reveal_area_index";
		public static readonly string ForcedRewardCardCount = "forced_reward_card_count";
		public static readonly string ForcedRewardCardTableIndex = "forced_reward_card_table_index";
		public static readonly string ForcedLostCardCount = "forced_lost_card_count";
		public static readonly string ForcedLostCardTableIndex = "forced_lost_card_table_index";
		public static readonly string IllustIndexColumn = "illust_index";
		public static readonly string PrefabIndexColumn = "prefab_index";
		public static readonly string StorySelectionIndexListColumn = "story_selection_index_list";
		public static readonly string SoundIndexColumn = "sound_index";
		public static readonly string StorySentenceIndexColumn = "story_sentence_index";
		public static readonly string Ko_krColumn = "ko_kr";
		public static readonly string StorySelectionIndexColumn = "story_selection_index";
		public static readonly string NextStorySentenceIndexListColumn = "next_story_sentence_index_list";
		public static readonly string BattleIndexColumn = "battle_index";
		public static readonly string NextStoryEventColumn = "next_story_event";
		public static readonly string MinigamePrefabIndexColumn = "minigame_prefab_index";
		public static readonly string TeleportAreaIndexColumn = "teleport_area_index";
		public static readonly string DeadEndingIndexColumn = "dead_ending_index";
		public static readonly string AddEndingIndexListColumn = "add_ending_index_list";
		public static readonly string StorySelectionRequireCurrentHpMinColumn = "story_selection_require_current_hp_min";
		public static readonly string StorySelectionRequireCurrentHpMaxColumn = "story_selection_require_current_hp_max";
		public static readonly string StorySelectionRequireHpMinColumn = "story_selection_require_hp_min";
		public static readonly string StorySelectionRequireHpMaxColumn = "story_selection_require_hp_max";
		public static readonly string StorySelectionRequireApMinColumn = "story_selection_require_ap_min";
		public static readonly string StorySelectionRequireApMaxColumn = "story_selection_require_ap_max";
		public static readonly string StorySelectionRequireStrMinColumn = "story_selection_require_str_min";
		public static readonly string StorySelectionRequireStrMaxColumn = "story_selection_require_str_max";
		public static readonly string StorySelectionRequireDexMinColumn = "story_selection_require_dex_min";
		public static readonly string StorySelectionRequireDexMaxColumn = "story_selection_require_dex_max";
		public static readonly string StorySelectionRequireIntMinColumn = "story_selection_require_int_min";
		public static readonly string StorySelectionRequireIntMaxColumn = "story_selection_require_int_max";
		public static readonly string StorySelectionRequireCardNumberColumn = "story_selection_require_card_number";
		public static readonly string StorySelectionRequireCardTableIndexColumn = "story_selection_require_card_table_index";
		public static readonly string StorySelectionRequireGoldMinColumn = "story_selection_require_gold_min";
		public static readonly string StorySelectionRequireGoldMaxColumn = "story_selection_require_gold_max";
		public static readonly string StorySelectionRequireAchievementPointMinColumn = "story_selection_require_achievement_point_min";
		public static readonly string StorySelectionRequireAchievementPointMaxColumn = "story_selection_require_achievement_point_max";
		public static readonly string StorySelectionRequireReputationIndexColumn = "story_selection_require_reputation_index";
		public static readonly string StorySelectionRequireReputationMaxColumn = "story_selection_require_reputation_max";
		public static readonly string StorySelectionRequireReputationMinColumn = "story_selection_require_reputation_min";
		public static readonly string RewardHpColumn = "reward_hp";
		public static readonly string RewardGoldColumn = "reward_gold";
		public static readonly string RewardExpColumn = "reward_exp";
		public static readonly string RewardCardCountColumn = "reward_card_count";
		public static readonly string RewardCardTableIndexColumn = "reward_card_table_index";
		public static readonly string LostCardCountColumn = "lost_card_count";
		public static readonly string LostCardTableIndexColumn = "lost_card_table_index";
		public static readonly string RewardEquipmentCountColumn = "reward_equipment_count";
		public static readonly string RewardEquipmentTableIndexColumn = "reward_equipment_table_index";
		public static readonly string RewardJounalIndexListColumn = "reward_jounal_index_list";
		public static readonly string ReputationIndexColumn = "reputation_index";
		public static readonly string ReputationAddValueColumn = "reputation_add_value";
		public static readonly string ReputationSetValueColumn = "reputation_set_value";
		public static readonly string RewardCollectionCharacterIndexList = "reward_collection_character_index_list";
		public static readonly string StoryEventIndexColumn = "story_event_index";
		public static readonly string IsInitialColumn = "is_initial";
		public static readonly string InitialStorySentenceIndexColumn = "initial_story_sentence_index";
		public static readonly string WeightColumn = "weight";
		public static readonly string PropertyColumn = "property";
		public static readonly string ReputationMinColumn = "reputation_min";
		public static readonly string ReputationMaxColumn = "reputation_max";
		public static readonly string BgmSoundIndexColumn = "bgm_sound_index";
		public static readonly string HintTypeColumn = "hint_type";
		public static readonly string TargetAreaIndexListColumn = "target_area_index_list";
		public static readonly string StoryShopIndexColumn = "story_shop_index";
		public static readonly string CardDiscountGradeColumn = "card_discount_grade";
		public static readonly string CardCountColumn = "card_count";
		public static readonly string CardTableIndexColumn = "card_table_index";
		public static readonly string EquipmentDiscountGradeColumn = "equipment_discount_grade";
		public static readonly string EquipmentCountColumn = "equipment_count";
		public static readonly string EquipmentTableIndexColumn = "equipment_table_index";
		public static readonly string StoryShopBuySelectionIndexColumn = "story_shop_buy_selection_index";
		public static readonly string StoryShopNonBuySelectionIndexColumn = "story_shop_non_buy_selection_index";
		public static readonly string MapIndexColumn = "map_index";
		public static readonly string ReputationRequirementPresetIndexColumn = "reputation_requirement_preset_index";
		public static readonly string ReputationRequirementPresetIndexListColumn = "reputation_requirement_preset_index_list";
		public static readonly string DeleteNextStoryEventColumn = "delete_next_story_event"; 
		public static readonly string EventTypeColumn = "event_type";
		public static readonly string IsExclusiveColumn = "is_exclusive";
		public static readonly string FactionEnumColumn = "faction_enum";
		public static readonly string IsRestColumn = "is_rest";
		public static readonly string IsShopColumn = "is_shop";
		public static readonly string IsDangerColumn = "is_danger";
		public static readonly string EndGameColumn = "end_game";
		public static readonly string EventIllustIndexColumn = "event_illust_index";
		public static readonly string ImagePathColumn = "image_path";
		public static readonly string ProductIDColumn = "product_id";
		public static readonly string NeedEnergyColumn = "need_energy";
	}
}
